### ISSUE TITLE
Unexpected crash

### ISSUE THREAD

**Issue by enryan** [ros-drivers/axis_camera#40]
Not sure if this is related to the driver itself. Axis node stops publishing, however it's still running.

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/devex/catkin_ws/src/axis_camera/nodes/axis.py", line 24, in run
    self.stream()
  File "/home/devex/catkin_ws/src/axis_camera/nodes/axis.py", line 30, in stream
    if self.openURL():
  File "/home/devex/catkin_ws/src/axis_camera/nodes/axis.py", line 62, in openURL
    self.fp = urllib2.urlopen(self.url, timeout=self.timeoutSeconds)
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 438, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 890, in http_error_401
    url, req, headers)
  File "/usr/lib/python2.7/urllib2.py", line 865, in http_error_auth_reqed
    response = self.retry_http_basic_auth(host, req, realm)
  File "/usr/lib/python2.7/urllib2.py", line 878, in retry_http_basic_auth
    return self.parent.open(req, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1207, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1180, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1038, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out

My launch file:

<launch>
  <arg name="username" default="root" />
  <arg name="password" default="mypassword"/>

  <group ns="axis_camera">
    <param name="width" value="640" />
    <param name="height" value="480" />
    <param name="hostname" value="axis_camera" />
    <param name="frame_id" value="axis_camera" />
     <param name="camera_info_url" value="PACKAGE://tt_navigation/platform_configs/${NAME}.yaml" />

    <node pkg="axis_camera" type="axis.py" name="axis">
      <param name="username" value="$(arg username)" />
      <param name="password" value="$(arg password)" />
    </node>

    <node pkg="image_transport" type="republish" name="republish" args="compressed in:=image_raw/ raw out:=image_raw" />
     	
    <node pkg="image_proc" type="image_proc" name="image_proc" />
	
  </group>
</launch>

**Comment by civerachb-cpr** [comment]
Are you able to ping the camera and/or access its web interface in a browser from the affected computer?
